name: Generate Directory Listing Page

permissions:
  contents: write  # Allows the workflow to write to the repository

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate the directory listing
      - name: Generate Directory Listing
        run: |
          #!/bin/bash

          # Start the HTML structure
          echo "<html><body><h1>Directory Listing</h1><ul>" > index.html

          # Function to recursively generate the directory listing
          generate_directory() {
            local dir=$1
            echo "<li><strong>Directory: $dir</strong><ul>" >> index.html

            # Loop through files in the directory
            for file in "$dir"/*; do
              # Exclude README.md, index.html, and hidden files/folders starting with a dot (.)
              if [[ "$file" == "./README.md" || "$file" == "./index.html" || "$file" == ./*/.??* ]]; then
                continue
              fi

              # If it's a directory, call the function recursively
              if [ -d "$file" ]; then
                generate_directory "$file"
              # If it's a file, create a link in the HTML
              elif [ -f "$file" ]; then
                echo "<li><a href=\"$file\">$file</a></li>" >> index.html
              fi
            done

            # Close the directory's list
            echo "</ul></li>" >> index.html
          }

          # Start generating from the current directory
          generate_directory .

          # Finish the HTML structure
          echo "</ul></body></html>" >> index.html

      # Step 3: Commit the changes
      - name: Commit and push changes
        run: |
          # Configure git user info
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Stage the changes
          git add index.html

          # Commit and push the changes
          if git commit -m 'Add updated index.html'; then
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
